### ISSUE TITLE
Import Clusters?

### ISSUE THREAD

**Issue by noqcks** [mongodb/mongodb-atlas-service-broker#58]
Hi there, 

I didn't see anything in the docs: is it possible to import clusters currently not managed in the Atlas Service Broker?

Thank you.

**Comment by noqcks** [comment]
cc: @fabianlindfors

**Comment by BenElgar** [comment]
Hi! I'm afraid there isn't currently a supported way of importing existing clusters so that they can be managed by the Atlas Service Broker.

**Comment by tomerliberman** [comment]
@BenElgar 
is there any workaround to get this to work? we want the service broker to be able to create users on an existing project & cluster (which was originally created by terraform, so we only want the users to be provisioned dynamically through kubernetes (using helm)
