### ISSUE TITLE
Developer Isolation?

### ISSUE THREAD

**Issue by noqcks** [mongodb/mongodb-atlas-service-broker#59]
Hi, 

Just curious on recommendations for rolling out the Atlas Service Broker for multiple development teams to use. What are the security implications? How do you ensure that different development teams cannot modify or delete the databases of others?

Ty.

**Comment by BenElgar** [comment]
Hi! This should be achievable by using standard Kubernetes Role-based access control. The Atlas Service Broker is stateless and thus holds no sensitive information so all teams can use the same instance. Standard Kubernetes RBAC should be used to restrict access to the relevant ServiceInstance, ServiceBinding and Secret resources. Does that answer your question?
