### ISSUE TITLE
Produce a complete connection string URI with credentials included

### ISSUE THREAD

**Issue by antonu17** [mongodb/mongodb-atlas-service-broker#60]
## Problem

Currently, Atlas OpenServiceBroker ServiceBinding returns credentials in 3 fields:

- SRV URL in the format: `mongodb+srv://my-atlas-cluster.mongodb.net`
- Username: `user`
- Password: `password`

Although this information is enough to connect to MongoDB, it requires applications to build a proper connection string from these data, e.g. `mongodb+srv://user:password@my-atlas-cluster.mongodb.net`

## Proposal

Make Atlas OpenServiceBroker produce a complete connection string usable for application out of the box.

**Comment by BenElgar** [comment]
Hi! Most drivers have a way of taking these as structured data. For instance the Node driver takes an `options` parameter that can contain an `auth` object that looks like this:
```javascript
{
  user: "my-username",
  password: "my-password"
}
```
See here: https://mongodb.github.io/node-mongodb-native/3.3/api/MongoClient.html

This should avoid the need for string concatenation in most cases. Is this insufficient for your use case?

**Comment by antonu17** [comment]
> Hi! Most drivers have a way of taking these as structured data. For instance the Node driver takes an `options` parameter that can contain an `auth` object that looks like this:
> 
> ```js
> {
>   user: "my-username",
>   password: "my-password"
> }
> ```
> 
> See here: https://mongodb.github.io/node-mongodb-native/3.3/api/MongoClient.html
> 
> This should avoid the need for string concatenation in most cases. Is this insufficient for your use case?

Hi @BenElgar!

Thanks for the advice. That will work, of course. In fact, this is what I had to do for one of our applications.

Let me provide a bit more details about our case. We have ~15 services using MongoDB. Written in PHP / Go, and running in Kubernetes. They all read configuration from the environment vars. And MongoDB connection string is just a single variable `MONGODB_DSN` in a [Standard Connection String Format](https://docs.mongodb.com/manual/reference/connection-string/#standard-connection-string-format).

Recently we decided to go with Atlas and use Service Catalog + Atlas OpenService Broker to provision MongoDB clusters in Atlas. After successful `ServiceBinding` we have a Kubernetes Secret with `url`, `username`, and `password`, so we have to define 3 env vars for `uri`, `username`, and `password` and modify mongodb connection method in each application.

Ideally, we don't want to touch the application code at all. It is just a matter of configuration, after all, isn't it? We would like to add the following configuration change in service's Pod template, but as I said, the `Secret` doesn't have a single field in Standard Connection String Format.

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
...
spec:
...
  template:
    spec:
...
      env:
        - name: DATABASE_DSN
          valueFrom:
            secretKeyRef:
            name: mydb-user
            key: connection_string
```

So far I have made this change to Atlas OpenService Broker code: https://github.com/mongodb/mongodb-atlas-service-broker/pull/61 and trying it out.

**Comment by BenElgar** [comment]
Gotcha, I understand the use case now and see how it would be useful. My concern is that this would encourage people to use the connection string directly and thus not make explicit choices about other parameters such as write concern, the defaults for which are likely to be unsuitable for a variety of use cases and should be considered carefully before production use.

That being said, perhaps the right answer is to hardcode safer defaults in the convenience connection string. Let me confer with the team and get back to you.

**Comment by antonu17** [comment]
I understand your concern. However, I thought it won't be a problem because atlas provides a connection string in [DNS Seedlist Connection Format](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format), which has its own way of passing default options via DNS TXT record.

**Comment by antonu17** [comment]
Quick update. I have deployed the patched version of the Atlas OpenService Broker (from #61) to our cluster, and confirm it works as expected.

**Comment by antonu17** [comment]
After using the patched version of the Atlas OpenService Broker (from #61) in production I collected feedback and got a better understanding of what should this feature look like. Please welcome #63 

## Background

ServiceBinding creates a Kubernetes Secret with 3 fields: `uri`, `username`, and `password`. If we run applications that require fully qualified [MongoDB connections string URI](https://docs.mongodb.com/manual/reference/connection-string/) this is not sufficient.

## Proposal

* Enable `ServiceBinding` to produce the `connection_string` field (in addition to `uri`, `username`, and `password`).
* Add `connectionString` parameter to `ServiceBinding` spec parameters to make the `connection_string` configurable.

## Documentation

After success binding, a Kubernetes Secret containing connection details has a `connection_string` field. By default it contains a connection string URI in the [DNS Seedlist Connection Format](https://docs.mongodb.com/manual/reference/connection-string/#connections-dns-seedlist) with credentials: e.g. `mongodb+srv://username:password@host`. The connections string can be configured through `connectionString` parameter of `ServiceBinding` resource's spec.

| Name            | Type                | Default | Description                                                             |
|-----------------|---------------------|---------|-------------------------------------------------------------------------|
| skipCredentials | bool                | false   | Controlls whether credentials should be included in the URI             |
| database        | string              | ''      | Database name porting of the connection string URI                      |
| format          | 'standard' or 'srv' | 'srv'   | Scheme portion of the connection string URI: `mongodb` or `mongodb+srv` |
| options         | list                | []      | Options portion of the connection string URI                            |

Example `ServiceBinding` resource spec:

```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: atlas-cluster-binding
spec:
  instanceRef:
    name: atlas-cluster-instance
  parameters:
    user:
      roles:
      ...
    connectionString:
      skipCredentials: false
      database: test
      format: standard
      options:
        connectTimeoutMS: 1000
        tlsAllowInvalidCertificates: true
        w: "majority"
```

**Comment by endrec** [comment]
We face the same problem using Spring Boot, which either accepts a URI, or a (host, username, password) triplet.

I like how #63 would work, is there any chance to make that part of the official package?

**Comment by jamesbroadhead** [comment]
Thanks for your interest in the AOSB. 
We've decided to deprecate this codebase, and are recommending that users switch to mongodb/mongodb-atlas-kubernetes instead.
