### ISSUE TITLE
Import resources from Mongo DB Cloud

### ISSUE THREAD

**Issue by eladazary** [mongodb/mongodb-atlas-service-broker#62]
Hi,

I would like to use the broker for user creation but in order to do that I would need to create a new instance (Cluster).
Am I missing something? Is there a way to create a user without creating a new cluster?

Regards,
Elad

**Comment by jamesbroadhead** [comment]
Thanks for your interest in the AOSB. 
We've decided to deprecate this codebase, and are recommending that users switch to [mongodb/mongodb-atlas-kubernetes](https://github.com/mongodb/mongodb-atlas-kubernetes) instead.
